using System.Collections.Generic;
using System.ComponentModel;

namespace ExifEditor.Services;

public enum AppLanguage { English, Polish }

public class LocalizationService : INotifyPropertyChanged
{
    public static LocalizationService Current { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;

    private AppLanguage _language = AppLanguage.English;

    public AppLanguage Language
    {
        get => _language;
        set
        {
            if (_language == value) return;
            _language = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
        }
    }

    private string T(string en, string pl) => _language == AppLanguage.Polish ? pl : en;

    // Menu
    public string MenuFile => T("File", "Plik");
    public string MenuOpenFolder => T("Open Folder...", "Otwórz folder...");
    public string MenuExit => T("Exit", "Zamknij");
    public string MenuTools => T("Tools", "Narzędzia");
    public string MenuGeneratePdf => T("Generate PDF Report", "Wygeneruj raport PDF");
    public string MenuThemeOcean => T("Theme: Ocean Blue", "Motyw: Ocean Blue");
    public string MenuThemeViolet => T("Theme: Violet Cyan", "Motyw: Violet Cyan");
    public string MenuLanguage => T("Language", "Język");
    public string MenuLanguageEnglish => T("English", "Angielski");
    public string MenuLanguagePolish => T("Polish", "Polski");
    public string MenuHelp => T("Help", "Pomoc");
    public string MenuAbout => T("About", "O programie");

    // Toolbar / panel
    public string SelectDirectory => T("Select Directory", "Wybierz folder");
    public string FileName => T("File Name:", "Nazwa pliku:");
    public string Show => T("Show", "Pokaż");
    public string Title => T("Title:", "Tytuł:");
    public string Scanned => T("Scanned:", "Zeskanowane:");
    public string UseRecent => T("Use Recent", "Ostatnie");
    public string Tags => T("Tags:", "Tagi:");
    public string Names => T("Names", "Nazwy");
    public string Numbers => T("Numbers", "Numery");
    public string Hidden => T("Hidden", "Ukryte");
    public string ClickToAddTag => T("Click on the image to add a tag", "Kliknij na zdjęciu aby dodać tag");
    public string Description => T("Description:", "Opis:");
    public string Save => T("Save", "Zapisz");

    // Status overlays
    public string GeneratingPdf => T("Generating PDF...", "Generowanie PDF...");
    public string SavingPdf => T("Saving PDF...", "Zapisywanie PDF...");

    // AddTagWindow
    public string EnterLabel => T("Enter label (e.g. first name and last name):", "Wprowadź etykietę (np. imię i nazwisko):");
    public string AddTagTitle => T("Add Tag", "Dodaj tag");
    public string EditTagTitle => T("Edit Tag", "Edytuj tag");
    public string Ok => T("OK", "OK");
    public string Cancel => T("Cancel", "Anuluj");

    // Confirm
    public string ConfirmDeleteTag(string label) => T(
        $"Are you sure you want to delete the tag \"{label}\"?",
        $"Czy na pewno usunąć tag „{label}”?");

    // Tooltips
    public string TooltipEditTag => T("Edit tag", "Edytuj tag");
    public string TooltipDeleteTag => T("Delete tag", "Usuń tag");

    // PDF report labels
    public string PdfImage => T("Image", "Zdjęcie");
    public string PdfLegend => T("Legend", "Legenda");
    public string PdfTitle => T("Title", "Tytuł");
    public string PdfScanned => T("Scanned", "Zeskanowane");
    public string PdfDescription => T("Description", "Opis");
    public string PdfReport => T("Report", "Raport");
    public string PdfGeneratedAt => T("Generated at", "Wygenerowano");
    public string PdfGeneratedBy => T("Generated by ExifEditor", "Wygenerowano przez ExifEditor");
}
