using ExifEditor.Services;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System;
using System.IO;
using System.Threading.Tasks;

public class PdfGeneratorService {
    private readonly DirectoryService _directoryService;

    private readonly ServiceFactory _serviceFactory;
    public PdfGeneratorService(DirectoryService directoryService, ServiceFactory serviceFactory) {
        QuestPDF.Settings.License = LicenseType.Community;
        QuestPDF.Settings.EnableDebugging = true;
        _directoryService = directoryService;
        _serviceFactory = serviceFactory;
    }

    public async Task GenerateReportAsync(string? dirPath)
    {
        var imagePaths = _directoryService.GetImagePaths(dirPath);

        await Task.Run(() =>
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));
                    
                    page.Header()
                        .PaddingTop(100)
                        .AlignCenter()
                        .Text("Report")
                        .Bold().FontSize(36).FontColor(Colors.Black);
                    
                    page.Content()
                        .AlignBottom()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(10);
                            var dateTime = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                            x.Item().Text($"Generated at {dateTime}");
                            x.Item().Text($"Generated by ExifEditor");
                        });
                });
                foreach(var imagePath in imagePaths) {
                    var imageService = _serviceFactory.CreateImageService(imagePath);
                    var imageName = Path.GetFileNameWithoutExtension(imagePath);
                    container.Page(page =>
                    {
                        page.Size(PageSizes.A4);
                        page.Margin(2, Unit.Centimetre);
                        page.PageColor(Colors.White);
                        page.DefaultTextStyle(x => x.FontSize(12));
                        
                        page.Header()
                            .Text($"Image: {imageName}")
                            .Bold().FontSize(24).FontColor(Colors.Black);
                        
                        page.Content()
                            .Column(x =>
                            {
                                x.Spacing(2);
                                x.Item().AlignCenter()
                                    .Width(200)
                                    .Image(imagePath)
                                    .WithCompressionQuality(ImageCompressionQuality.VeryLow);
                                x.Item().Text(text => {
                                    text.Span($"Artist: ").Bold();
                                    text.Span($"{imageService.GetArtist()}");
                                });
                                x.Item().Text(text => {
                                    text.Span($"Description: ").Bold();
                                    text.Span($"{imageService.GetDescription()}");
                                });
                            });

                        page.Footer()
                            .AlignRight()
                            .Text(x =>
                            {
                                x.CurrentPageNumber();
                                x.Span($" of ");
                                x.TotalPages();
                            });
                    });
                }
            })
            .GeneratePdf("report.pdf");
        });
    }
}