using ExifEditor.Models;
using ExifEditor.Services;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SkiaSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

public class PdfGeneratorService {
    private readonly DirectoryService _directoryService;

    private readonly ServiceFactory _serviceFactory;
    public PdfGeneratorService(DirectoryService directoryService, ServiceFactory serviceFactory) {
        QuestPDF.Settings.License = LicenseType.Community;
        QuestPDF.Settings.EnableDebugging = true;
        _directoryService = directoryService;
        _serviceFactory = serviceFactory;
    }

    public async Task GenerateReportAsync(string? dirPath, IProgress<(int current, int total)>? progress = null)
    {
        var imagePaths = _directoryService.GetImagePaths(dirPath);
        var total = imagePaths.Count;
        progress?.Report((0, total));

        await Task.Run(() =>
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .PaddingTop(100)
                        .AlignCenter()
                        .Text("Report")
                        .Bold().FontSize(36).FontColor(Colors.Black);

                    page.Content()
                        .AlignBottom()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(10);
                            var dateTime = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                            x.Item().Text($"Generated at {dateTime}");
                            x.Item().Text($"Generated by ExifEditor");
                        });
                });
                var processed = 0;
                foreach(var imagePath in imagePaths) {
                    var imageService = _serviceFactory.CreateImageService(imagePath);
                    var imageName = Path.GetFileNameWithoutExtension(imagePath);
                    container.Page(page =>
                    {
                        page.Size(PageSizes.A4);
                        page.Margin(2, Unit.Centimetre);
                        page.PageColor(Colors.White);
                        page.DefaultTextStyle(x => x.FontSize(12));
                        
                        page.Header()
                            .Text($"Image: {imageName}")
                            .Bold().FontSize(24).FontColor(Colors.Black);
                        
                        var descriptionData = DescriptionData.Deserialize(imageService.GetDescription());

                        // A4 content area: 170mm wide x ~257mm tall (after 2cm margins + header/footer)
                        // Image zone: 2/3 of content height, description zone: 1/3
                        const float pageContentWidth = 170f; // mm
                        const float imageZoneHeight = 170f;  // ~2/3 of content area

                        // Calculate image display size preserving aspect ratio
                        using var bitmap = SKBitmap.Decode(imagePath);
                        var imgW = bitmap?.Width ?? 1;
                        var imgH = bitmap?.Height ?? 1;
                        var scale = Math.Min(pageContentWidth / imgW, imageZoneHeight / imgH);
                        var displayWidth = imgW * scale;
                        var displayHeight = imgH * scale;

                        page.Content()
                            .Column(x =>
                            {
                                x.Spacing(8);

                                // Image section — max 2/3 of page
                                x.Item().Height(imageZoneHeight, Unit.Millimetre)
                                    .AlignCenter().AlignMiddle()
                                    .Width(displayWidth, Unit.Millimetre)
                                    .Height(displayHeight, Unit.Millimetre)
                                    .Layers(layers =>
                                    {
                                        layers.PrimaryLayer()
                                            .Image(imagePath)
                                            .WithCompressionQuality(ImageCompressionQuality.Low)
                                            .FitArea();

                                        if (descriptionData.Tags is { Count: > 0 })
                                        {
                                            layers.Layer()
                                                .Canvas((canvas, size) =>
                                                {
                                                    DrawTagMarkers(canvas, size, descriptionData.Tags);
                                                });
                                        }
                                    });

                                // Description section — remaining 1/3 of page
                                if (!string.IsNullOrWhiteSpace(descriptionData.Scanned)) {
                                    x.Item().Text(text => {
                                        text.Span("Scanned: ").Bold();
                                        text.Span($"{descriptionData.Scanned}");
                                    });
                                }
                                x.Item().Text(text => {
                                    text.Span("Description: ").Bold();
                                    text.Span($"{descriptionData.Description}");
                                });
                                if (descriptionData.Tags is { Count: > 0 }) {
                                    x.Item().Text("Tags:").Bold();
                                    foreach (var tag in descriptionData.Tags) {
                                        x.Item().Text($"  - {tag.Label} ({tag.AnchorX * 100:F0}%, {tag.AnchorY * 100:F0}%)");
                                    }
                                }
                            });

                        page.Footer()
                            .AlignRight()
                            .Text(x =>
                            {
                                x.CurrentPageNumber();
                                x.Span($" of ");
                                x.TotalPages();
                            });
                    });
                    processed++;
                    progress?.Report((processed, total));
                }
            })
            .GeneratePdf(Path.Combine(dirPath!, $"report_{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.pdf"));
        });
    }

    private static void DrawTagMarkers(SKCanvas canvas, Size size, List<ImageTag> tags)
    {
        var markerRadius = 4f;

        using var markerPaint = new SKPaint
        {
            Color = new SKColor(88, 166, 255), // AccentColor
            IsAntialias = true,
            Style = SKPaintStyle.Fill
        };

        using var strokePaint = new SKPaint
        {
            Color = SKColors.White,
            IsAntialias = true,
            Style = SKPaintStyle.Stroke,
            StrokeWidth = 1.5f
        };

        using var labelBgPaint = new SKPaint
        {
            Color = new SKColor(22, 27, 34, 200), // TagLabelBgColor
            IsAntialias = true,
            Style = SKPaintStyle.Fill
        };

        using var labelTextPaint = new SKPaint
        {
            Color = SKColors.White,
            IsAntialias = true,
            TextSize = 7f
        };

        using var linePaint = new SKPaint
        {
            Color = SKColors.White,
            IsAntialias = true,
            Style = SKPaintStyle.Stroke,
            StrokeWidth = 1f
        };

        foreach (var tag in tags)
        {
            var cx = (float)(tag.AnchorX * size.Width);
            var cy = (float)(tag.AnchorY * size.Height);

            // Draw label with connector line
            if (!string.IsNullOrEmpty(tag.Label))
            {
                var labelX = cx + (float)(tag.EffectiveLabelOffsetX * size.Width);
                var labelY = cy + (float)(tag.EffectiveLabelOffsetY * size.Height);

                var textWidth = labelTextPaint.MeasureText(tag.Label);
                var padding = 3f;
                var rect = new SKRect(
                    labelX - padding,
                    labelY - labelTextPaint.TextSize - padding,
                    labelX + textWidth + padding,
                    labelY + padding);

                // Draw line from marker to closest edge of label rect
                var targetX = Math.Clamp(cx, rect.Left, rect.Right);
                var targetY = Math.Clamp(cy, rect.Top, rect.Bottom);
                canvas.DrawLine(cx, cy, targetX, targetY, linePaint);

                canvas.DrawRoundRect(rect, 3, 3, labelBgPaint);
                canvas.DrawText(tag.Label, labelX, labelY, labelTextPaint);
            }

            // Draw marker dot (on top of line)
            canvas.DrawCircle(cx, cy, markerRadius, markerPaint);
            canvas.DrawCircle(cx, cy, markerRadius, strokePaint);
        }
    }
}