name: CI

on:
  push:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build (linux-only) 
      env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: contains(matrix.os, 'ubuntu')  
      run: |
        echo ${LATEST_TAG_DISTANCE}
        dotnet tool install -g dotnet-deb
        dotnet deb install
        dotnet-deb -c Release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ExifEditor-${{ matrix.os }}
        path: /home/runner/work/ExifEditor/ExifEditor/bin/Release/net6.0/ExifEditor.0.1.0.deb